root = "."
tmp_dir = "tmp/core"

[build]
  bin = "./tmp/core/main"
  cmd = "go build -o ./tmp/core/main ./cmd/microvault/main.go"
  exclude_dir = ["tmp", "vendor", "credit", "cmd/microvault/docs"]
  include_dir = ["core", "cmd/microvault"]
  include_ext = ["go"]
  delay = 1000
