-- Rename loans.loan_number → loans.loan_reference.
--
-- "Number" implies an ordinal (1, 2, 3...) but the value is an opaque
-- alphanumeric reference (e.g. "LN-018F3A2B1C-A7F2"). User-facing SMS copy
-- already calls it "Ref:" — this aligns the column with the language.
--
-- The unique index is recreated to match the new name. Postgres renames the
-- index automatically when the column is renamed (idx_loans_loan_number was
-- generated by GORM's uniqueIndex tag, so it follows the column).

ALTER TABLE loans RENAME COLUMN loan_number TO loan_reference;
