ALTER TABLE loans DROP COLUMN IF EXISTS ramp_fee_usd;
ALTER TABLE loans DROP COLUMN IF EXISTS ramp_fee_local;

ALTER TABLE loans ADD COLUMN IF NOT EXISTS service_fee_usd BIGINT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS service_fee_local BIGINT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS partner_fee_usd BIGINT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS partner_fee_local BIGINT;
